EEVA/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EEVA.Domain;
using EEVA.Domain.Models;
using EEVA.Domain.DataManager;
using Microsoft.AspNetCore.Authorization;
using EEVA.Web.Models;

namespace EEVA.Web.Controllers
{
    [Authorize(Roles = "Teacher, Admin")]
    public class CourseController : Controller
    {
        private readonly ExamManager _examManager;
        private readonly CourseManager _courseManager;
        private readonly ContactManager _contactManager;
        private readonly QuestionManager _questionManager;

        public CourseController(EEVAContext context)
        {
            _examManager = new ExamManager(context);
            _courseManager = new CourseManager(context);
            _contactManager = new ContactManager(context);
            _questionManager = new QuestionManager(context);
        }

        // GET: Course
        
        public IActionResult Index(string searchString, string currentFilter, int? pageNumber, string message)
        {
            ViewBag.Message = message;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            List<CourseViewModel> courseViewModels = new List<CourseViewModel>();
            IEnumerable<Course> courses;

            if (!string.IsNullOrEmpty(searchString))
            {
                courses = _courseManager.Search(searchString);
            }
            else courses = _courseManager.GetAll();

            foreach (Course c in courses)
            {
                courseViewModels.Add(MapToCourseViewModel(c));
            }

            int pageSize = 8;
            return View(PaginatedList<CourseViewModel>.Create(courseViewModels, pageNumber ?? 1, pageSize));
        }

        // GET: Course/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CourseViewModel courseViewModel = MapToCourseViewModel(_courseManager.Get(id));

            if (courseViewModel == null)
            {
                return NotFound();
            }

            return View(courseViewModel);
        }

        
        // GET: Course/Create
        public IActionResult Create()
        {
            return View(NewCourseViewModel());
        }

        // POST: Course/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,CourseName,CourseYear")] CourseViewModel courseViewModel)
        {
            if (ModelState.IsValid)
            {
                Course course = MapToCourse(courseViewModel);
                _courseManager.Add(course);
                return RedirectToAction(nameof(Index), new { message = "create"});
            }
            return View(courseViewModel);
        }

        [Authorize(Roles = "Teacher, Admin")]
        // GET: Course/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Course course = _courseManager.Get(id);
            if (course == null)
            {
                return NotFound();
            }
            else
            {
                CourseViewModel courseViewModel = MapToCourseViewModel(course);
                return View(courseViewModel);
            }
        }

        // POST: Course/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,CourseName,CourseYear")] CourseViewModel courseViewModel)
        {
            if (id != courseViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Course course = MapToCourse(courseViewModel);
                    _courseManager.Update(course);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(courseViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { message = "edit"});
            }
            return View();
        }

        [Authorize(Roles = "Teacher, Admin")]
        // GET: Course/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            CourseViewModel courseViewModel = MapToCourseViewModel(_courseManager.Get(id));

            if (courseViewModel == null)
            {
                return NotFound();
            }

            return View(courseViewModel);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Course course = _courseManager.Get(id);
            _courseManager.Delete(course);
            return RedirectToAction(nameof(Index), new { message = "delete" });
        }

        // Redirect to the related details of a Question
        public ActionResult QuestionDetails(int? id)
        {
            return RedirectToAction("Details", "Question", new { id });
        }

        // Redirect to edit Question
        public ActionResult QuestionEdit(int? id)
        {
            return RedirectToAction("Edit", "Question", new { id });
        }

        // Redirect to the related details of an Exam
        public ActionResult ExamDetails(int? id)
        {
            return RedirectToAction("Details", "Exam", new { id });
        }

        // Redirect to edit Exam
        public ActionResult ExamEdit(int? id)
        {
            return RedirectToAction("Edit", "Exam", new { id });
        }

        private bool CourseExists(int id)
        {
            if (_courseManager.Get(id) != null)
            {
                return true;
            }
            else return false;
        }

        //Mapping Course to CourseViewModel
        private CourseViewModel MapToCourseViewModel(Course c)
        {
            return new CourseViewModel(
                c.Id,
                c.CourseName,
                c.CourseYear,
                c.Questions,
                c.Exams);
        }

        //Mapping CourseViewModel to Course
        private Course MapToCourse(CourseViewModel courseViewModel)
        {
            return new Course(
                courseViewModel.Id,
                courseViewModel.CourseName,
                courseViewModel.CourseYear,
                courseViewModel.Questions,
                courseViewModel.Exams
                );
        }

        //Creating blank CourseViewModel
        private CourseViewModel NewCourseViewModel()
        {
            return new CourseViewModel();
        }
    }
}

EEVA/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EEVA.Domain;
using EEVA.Domain.Models;
using EEVA.Domain.DataManager;
using Microsoft.AspNetCore.Authorization;
using EEVA.Web.Models;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Identity;

namespace EEVA.Web.Controllers
{
    [Authorize(Roles = "Teacher, Admin")]
    public class StudentController : Controller
    {
        private readonly ContactManager _contactManager;
        private readonly UserManager<IdentityUser> _userManager;

        public StudentController(UserManager<IdentityUser> userManager, EEVAContext context)
        {
            _userManager = userManager;
            _contactManager = new ContactManager(context);
        }


        public IActionResult Index(string searchString, string currentFilter, int? pageNumber, string message)
        {
            ViewBag.Message = message;
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            List<StudentViewModel> studentViewModels = new List<StudentViewModel>();
            IEnumerable<Contact> students;

            if (!string.IsNullOrEmpty(searchString))
            {
                students = _contactManager.Search(searchString);
            }
            else students = _contactManager.GetAll();

            foreach (Contact c in students)
            {
                if (c is Student)
                {
                    Student student = (Student) c;
                    studentViewModels.Add(MapToStudentViewModel(student));
                }

            }

            int pageSize = 8;
            return View(PaginatedList<StudentViewModel>.Create(studentViewModels, pageNumber ?? 1, pageSize));
        }

        

        // GET: Student/Details/5
        public IActionResult Details(int? id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            StudentViewModel studentViewModel = MapToStudentViewModel((Student)_contactManager.Get(id));

            if (studentViewModel == null)
            {
                return NotFound();
            }

            return View(studentViewModel);
        }

        // GET: Student/Create
        public IActionResult Create()
        {
            return View(new StudentViewModel());
        }

        // POST: Student/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,FirstName,LastName,Email,PhoneNumber")] StudentViewModel studentViewModel)
        {
            if (ModelState.IsValid)
            {
                Student student = MapToStudent(studentViewModel);
                _contactManager.Add(student);
                return RedirectToAction(nameof(Index), new { message = "create"});
            }
            return View();
        }

        // GET: Student/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            Student student = (Student)_contactManager.Get(id);
            if (student == null)
            {
                return NotFound();
            }
            else
            {
                StudentViewModel studentViewModel = MapToStudentViewModel(student);
                return View(studentViewModel);
            }
        }

        // POST: Student/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, StudentViewModel studentViewModel)
        {
            if (id != studentViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Student student = MapToStudent(studentViewModel);
                    _contactManager.Update(student);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(studentViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { message = "edit"});
            }
            return View();
        }

        // GET: Student/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            StudentViewModel studentViewModel = MapToStudentViewModel((Student)_contactManager.Get(id));

            if (studentViewModel == null)
            {
                return NotFound();
            }

            return View(studentViewModel);
        }

        // POST: Student/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, string email)
        {
            
            Student student = (Student)_contactManager.Get(id);
            _contactManager.Delete(student);



            //delete user and his roles from AspUsers
            var user = await _userManager.FindByEmailAsync(email);
            if (user != null)
            {
                var logins = await _userManager.GetLoginsAsync(user);
                var rolesForUser = await _userManager.GetRolesAsync(user);

                using (var transaction = _contactManager._eevaContext.Database.BeginTransaction())
                {
                    IdentityResult result = IdentityResult.Success;
                    foreach (var login in logins)
                    {
                        result = await _userManager.RemoveLoginAsync(user, login.LoginProvider, login.ProviderKey);
                        if (result != IdentityResult.Success)
                            break;
                    }
                    if (result == IdentityResult.Success)
                    {
                        foreach (var item in rolesForUser)
                        {
                            result = await _userManager.RemoveFromRoleAsync(user, item);
                            if (result != IdentityResult.Success)
                                break;
                        }
                    }
                    if (result == IdentityResult.Success)
                    {
                        result = await _userManager.DeleteAsync(user);
                        if (result == IdentityResult.Success)
                            transaction.Commit(); //only commit if user and all his logins/roles have been deleted  
                    }
                }

            }
            

            return RedirectToAction(nameof(Index), new { message = "delete"});
        }


        private bool StudentExists(int id)
        {
            if (_contactManager.Get(id) != null)
            {
                return true;
            }
            else return false;
        }


        private StudentViewModel MapToStudentViewModel(Student student)
        {
            return new StudentViewModel(
                student.Id,
                student.FirstName,
                student.LastName,
                student.FullName,
                student.Email,
                student.PhoneNumber);
        }

        private Student MapToStudent(StudentViewModel studentViewModel)
        {
            return new Student(
                studentViewModel.Id,
                studentViewModel.FirstName,
                studentViewModel.LastName,
                studentViewModel.Email,
                studentViewModel.PhoneNumber
                );
        }
    }
}

EEVA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EEVA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
 
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <a class="navbar-brand">
                <img src="~/img/UCLL_LOGO_RGB.png" width="120" height="50" class="form-inline" />
            </a>
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Exam" asp-action="Index">Exams</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="Index">Questions</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Users
                                </a>
                                <div class="dropdown-menu text-dark" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-dark" asp-controller="Teacher" asp-action="Index">Teachers</a>
                                    <a class="dropdown-item text-dark" asp-controller="Student" asp-action="Index">Students</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="StudentExam" asp-action="Index">Student Exams</a>
                            </li>

                        }
                        
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="StudentExam" asp-action="Index">My Exams</a>
                            </li>
                        



                    </ul>



                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Matthias Somay & Kenneth Van Den Borne
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>